// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	dms "github.com/Mellanox/nic-configuration-operator/pkg/dms"
	mock "github.com/stretchr/testify/mock"
)

// DMSManager is an autogenerated mock type for the DMSManager type
type DMSManager struct {
	mock.Mock
}

// GetDMSClientByPCIAddress provides a mock function with given fields: pciDeviceAddr
func (_m *DMSManager) GetDMSClientByPCIAddress(pciDeviceAddr string) (dms.DMSClient, error) {
	ret := _m.Called(pciDeviceAddr)

	if len(ret) == 0 {
		panic("no return value specified for GetDMSClientByPCIAddress")
	}

	var r0 dms.DMSClient
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (dms.DMSClient, error)); ok {
		return rf(pciDeviceAddr)
	}
	if rf, ok := ret.Get(0).(func(string) dms.DMSClient); ok {
		r0 = rf(pciDeviceAddr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dms.DMSClient)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pciDeviceAddr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDMSManager creates a new instance of DMSManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDMSManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *DMSManager {
	mock := &DMSManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
