version: "2"

run:
  timeout: 10m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    generated: lax
    rules:
      - path: "api/*"
        linters:
          - lll
      - path: "internal/*"
        linters:
          - dupl
          - lll
      - path: "pkg/*"
        linters:
          - dupl
          - lll

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
