// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	"context"

	v1alpha1 "github.com/Mellanox/nic-configuration-operator/api/v1alpha1"
	"github.com/Mellanox/nic-configuration-operator/pkg/udev"
	mock "github.com/stretchr/testify/mock"
)

// UdevManager is an autogenerated mock type for the UdevManager type
type UdevManager struct {
	mock.Mock
}

// ApplyUdevRules provides a mock function with given fields: ctx, devices
func (_m *UdevManager) ApplyUdevRules(ctx context.Context, devices []*v1alpha1.NicDevice) (map[string]udev.ExpectedInterfaceNames, bool, error) {
	ret := _m.Called(ctx, devices)

	if len(ret) == 0 {
		panic("no return value specified for ApplyUdevRules")
	}

	var r0 map[string]udev.ExpectedInterfaceNames
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []*v1alpha1.NicDevice) (map[string]udev.ExpectedInterfaceNames, bool, error)); ok {
		return rf(ctx, devices)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*v1alpha1.NicDevice) map[string]udev.ExpectedInterfaceNames); ok {
		r0 = rf(ctx, devices)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]udev.ExpectedInterfaceNames)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*v1alpha1.NicDevice) bool); ok {
		r1 = rf(ctx, devices)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, []*v1alpha1.NicDevice) error); ok {
		r2 = rf(ctx, devices)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewUdevManager creates a new instance of UdevManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUdevManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *UdevManager {
	mock := &UdevManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
