// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/Mellanox/nic-configuration-operator/pkg/types"
)

// NVConfigUtils is an autogenerated mock type for the NVConfigUtils type
type NVConfigUtils struct {
	mock.Mock
}

// QueryNvConfig provides a mock function with given fields: ctx, pciAddr, parameters
func (_m *NVConfigUtils) QueryNvConfig(ctx context.Context, pciAddr string, parameters []string) (types.NvConfigQuery, error) {
	ret := _m.Called(ctx, pciAddr, parameters)

	if len(ret) == 0 {
		panic("no return value specified for QueryNvConfig")
	}

	var r0 types.NvConfigQuery
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (types.NvConfigQuery, error)); ok {
		return rf(ctx, pciAddr, parameters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) types.NvConfigQuery); ok {
		r0 = rf(ctx, pciAddr, parameters)
	} else {
		r0 = ret.Get(0).(types.NvConfigQuery)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, pciAddr, parameters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetNvConfig provides a mock function with given fields: pciAddr
func (_m *NVConfigUtils) ResetNvConfig(pciAddr string) error {
	ret := _m.Called(pciAddr)

	if len(ret) == 0 {
		panic("no return value specified for ResetNvConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(pciAddr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetNvConfigParameter provides a mock function with given fields: pciAddr, paramName, paramValue
func (_m *NVConfigUtils) SetNvConfigParameter(pciAddr string, paramName string, paramValue string) error {
	ret := _m.Called(pciAddr, paramName, paramValue)

	if len(ret) == 0 {
		panic("no return value specified for SetNvConfigParameter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(pciAddr, paramName, paramValue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetNvConfigParametersBatch provides a mock function with given fields: pciAddr, params, withDefault, force
func (_m *NVConfigUtils) SetNvConfigParametersBatch(pciAddr string, params map[string]string, withDefault bool, force bool) (types.ApplyStatus, error) {
	ret := _m.Called(pciAddr, params, withDefault, force)

	if len(ret) == 0 {
		panic("no return value specified for SetNvConfigParametersBatch")
	}

	var r0 types.ApplyStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]string, bool, bool) (types.ApplyStatus, error)); ok {
		return rf(pciAddr, params, withDefault, force)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]string, bool, bool) types.ApplyStatus); ok {
		r0 = rf(pciAddr, params, withDefault, force)
	} else {
		r0 = ret.Get(0).(types.ApplyStatus)
	}

	if rf, ok := ret.Get(1).(func(string, map[string]string, bool, bool) error); ok {
		r1 = rf(pciAddr, params, withDefault, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetSystemConf provides a mock function with given fields: ctx, pciAddr, conf, asic, force
func (_m *NVConfigUtils) SetSystemConf(ctx context.Context, pciAddr string, conf string, asic int, force bool) error {
	ret := _m.Called(ctx, pciAddr, conf, asic, force)

	if len(ret) == 0 {
		panic("no return value specified for SetSystemConf")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, bool) error); ok {
		r0 = rf(ctx, pciAddr, conf, asic, force)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateSystemConf provides a mock function with given fields: ctx, pciAddr, conf, asic
func (_m *NVConfigUtils) ValidateSystemConf(ctx context.Context, pciAddr string, conf string, asic int) (bool, []string, error) {
	ret := _m.Called(ctx, pciAddr, conf, asic)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSystemConf")
	}

	var r0 bool
	var r1 []string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (bool, []string, error)); ok {
		return rf(ctx, pciAddr, conf, asic)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) bool); ok {
		r0 = rf(ctx, pciAddr, conf, asic)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) []string); ok {
		r1 = rf(ctx, pciAddr, conf, asic)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int) error); ok {
		r2 = rf(ctx, pciAddr, conf, asic)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewNVConfigUtils creates a new instance of NVConfigUtils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNVConfigUtils(t interface {
	mock.TestingT
	Cleanup(func())
}) *NVConfigUtils {
	mock := &NVConfigUtils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
