/*
2025 NVIDIA CORPORATION & AFFILIATES
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package mocks

import (
	context "context"

	nvconfig "github.com/Mellanox/nic-configuration-operator/pkg/nvconfig"
)

// This file is hand-maintained (NOT generated by mockery). ValidateSystemConfDetailed is part of the
// optional nvconfig.SystemConfValidator extension, not the base NVConfigUtils interface, so regenerating
// NVConfigUtils.go must not drop it. The compile-time assertions below fail the build if *NVConfigUtils
// ever stops satisfying either interface.
var (
	_ nvconfig.NVConfigUtils       = (*NVConfigUtils)(nil)
	_ nvconfig.SystemConfValidator = (*NVConfigUtils)(nil)
)

// ValidateSystemConfDetailed provides a mock function with given fields: ctx, pciAddr, conf, asic
func (_m *NVConfigUtils) ValidateSystemConfDetailed(ctx context.Context, pciAddr string, conf string, asic int) (*nvconfig.SystemConfValidationResult, error) {
	ret := _m.Called(ctx, pciAddr, conf, asic)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSystemConfDetailed")
	}

	var r0 *nvconfig.SystemConfValidationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (*nvconfig.SystemConfValidationResult, error)); ok {
		return rf(ctx, pciAddr, conf, asic)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) *nvconfig.SystemConfValidationResult); ok {
		r0 = rf(ctx, pciAddr, conf, asic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nvconfig.SystemConfValidationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, pciAddr, conf, asic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
