# permissions for end users to view nicconfigurationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nic-configuration-operator
    app.kubernetes.io/managed-by: kustomize
  name: nicconfigurationtemplate-viewer-role
rules:
- apiGroups:
  - configuration.net.nvidia.com
  resources:
  - nicconfigurationtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.net.nvidia.com
  resources:
  - nicconfigurationtemplates/status
  verbs:
  - get
