apiVersion: configuration.net.nvidia.com/v1alpha1
kind: NicConfigurationTemplate
metadata:
  labels:
    app.kubernetes.io/name: nic-configuration-operator
    app.kubernetes.io/managed-by: kustomize
  name: nicconfigurationtemplate-sample
spec:
  # TODO(user): Add fields here
