apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nic-configuration-daemon
  namespace: {{.Namespace}}
  labels:
    app.kubernetes.io/name: nic-configuration-daemon
    app.kubernetes.io/created-by: nic-configuration-operator
    app.kubernetes.io/part-of: nic-configuration-operator
  {{- if eq .ClusterType "openshift" }}
  annotations:
    release.openshift.io/version: "{{.ReleaseVersion}}"
  {{- end }}
spec:
  selector:
    matchLabels:
      app: nic-configuration-daemon
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: nic-configuration-daemon
        {{- if eq .ClusterType "openshift" }}
        openshift.io/required-scc: privileged
        {{- end }}
      labels:
        app: nic-configuration-daemon
        component: network
        type: infra
        {{- if eq .ClusterType "openshift" }}
        openshift.io/component: network
        {{- end }}
    spec:
      serviceAccountName: {{.ServiceAccountName}}
      terminationGracePeriodSeconds: 10
      hostNetwork: true
      hostPID: true
      priorityClassName: system-node-critical
      {{- if .ImagePullSecrets }}
      imagePullSecrets:
      {{- range .ImagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .NodeSelector }}
      nodeSelector: {{.NodeSelector}}
      {{- end }}
      containers:
        - image: {{.Image}}
          name: nic-configuration-daemon
          securityContext:
            privileged: true
          {{- if .Resources }}
          resources: {{.Resources}}
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .LogLevel }}
            - name: LOG_LEVEL
              value: {{.LogLevel}}
            {{- end}}
          volumeMounts:
            - name: sys
              mountPath: /sys
              readOnly: false
            - name: proc
              mountPath: /proc
              readOnly: false
            - name: host
              mountPath: /host
              readOnly: true
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: proc
          hostPath:
            path: /proc
        - name: host
          hostPath:
            path: /
