// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	v1alpha1 "github.com/Mellanox/nic-configuration-operator/api/v1alpha1"
	spectrumx "github.com/Mellanox/nic-configuration-operator/pkg/spectrumx"

	mock "github.com/stretchr/testify/mock"
)

// PlanManager is an autogenerated mock type for the PlanManager type.
type PlanManager struct {
	mock.Mock
}

// PreparePlan provides a mock function with given fields: ctx, devices, stage.
func (_m *PlanManager) PreparePlan(
	ctx context.Context,
	devices []*v1alpha1.NicDevice,
	stage spectrumx.PlanStage,
) error {
	ret := _m.Called(ctx, devices, stage)

	if len(ret) == 0 {
		panic("no return value specified for PreparePlan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*v1alpha1.NicDevice, spectrumx.PlanStage) error); ok {
		r0 = rf(ctx, devices, stage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GetPreparedPlan provides a mock function with given fields: device, stage.
func (_m *PlanManager) GetPreparedPlan(device *v1alpha1.NicDevice, stage spectrumx.PlanStage) (*spectrumx.Plan, error) {
	ret := _m.Called(device, stage)

	if len(ret) == 0 {
		panic("no return value specified for GetPreparedPlan")
	}

	var r0 *spectrumx.Plan
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.NicDevice, spectrumx.PlanStage) (*spectrumx.Plan, error)); ok {
		return rf(device, stage)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.NicDevice, spectrumx.PlanStage) *spectrumx.Plan); ok {
		r0 = rf(device, stage)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*spectrumx.Plan)
	}
	if rf, ok := ret.Get(1).(func(*v1alpha1.NicDevice, spectrumx.PlanStage) error); ok {
		r1 = rf(device, stage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewPlanManager creates a new instance of PlanManager and registers mock assertions.
func NewPlanManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlanManager {
	mock := &PlanManager{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
