// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/Mellanox/nic-configuration-operator/api/v1alpha1"
	spectrumx "github.com/Mellanox/nic-configuration-operator/pkg/spectrumx"
)

// SpectrumXManager is an autogenerated mock type for the SpectrumXManager type.
type SpectrumXManager struct {
	mock.Mock
}

func (_m *SpectrumXManager) InstallBlueprintsData(archive []byte) error {
	ret := _m.Called(archive)
	if len(ret) == 0 {
		panic("no return value specified for InstallBlueprintsData")
	}
	return ret.Error(0)
}

func (_m *SpectrumXManager) RemoveBlueprintsData() error {
	ret := _m.Called()
	if len(ret) == 0 {
		panic("no return value specified for RemoveBlueprintsData")
	}
	return ret.Error(0)
}

func (_m *SpectrumXManager) PreparePlan(ctx context.Context, devices []*v1alpha1.NicDevice, stage spectrumx.PlanStage) error {
	ret := _m.Called(ctx, devices, stage)
	if len(ret) == 0 {
		panic("no return value specified for PreparePlan")
	}
	return ret.Error(0)
}

func (_m *SpectrumXManager) GetPreparedPlan(device *v1alpha1.NicDevice, stage spectrumx.PlanStage) (*spectrumx.Plan, error) {
	ret := _m.Called(device, stage)
	if len(ret) == 0 {
		panic("no return value specified for GetPreparedPlan")
	}
	if function, ok := ret.Get(0).(func(*v1alpha1.NicDevice, spectrumx.PlanStage) (*spectrumx.Plan, error)); ok {
		return function(device, stage)
	}
	var plan *spectrumx.Plan
	if function, ok := ret.Get(0).(func(*v1alpha1.NicDevice, spectrumx.PlanStage) *spectrumx.Plan); ok {
		plan = function(device, stage)
	} else if value := ret.Get(0); value != nil {
		plan = value.(*spectrumx.Plan)
	}
	var err error
	if function, ok := ret.Get(1).(func(*v1alpha1.NicDevice, spectrumx.PlanStage) error); ok {
		err = function(device, stage)
	} else {
		err = ret.Error(1)
	}
	return plan, err
}

func (_m *SpectrumXManager) RunDocaSpcXCC(port v1alpha1.NicDevicePortSpec) error {
	ret := _m.Called(port)
	if len(ret) == 0 {
		panic("no return value specified for RunDocaSpcXCC")
	}
	return ret.Error(0)
}

func (_m *SpectrumXManager) GetCCTerminationChannel() <-chan string {
	ret := _m.Called()
	if len(ret) == 0 {
		panic("no return value specified for GetCCTerminationChannel")
	}
	if value := ret.Get(0); value != nil {
		return value.(<-chan string)
	}
	return nil
}

// NewSpectrumXManager creates a SpectrumXManager mock.
func NewSpectrumXManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpectrumXManager {
	manager := &SpectrumXManager{}
	manager.Mock.Test(t)
	t.Cleanup(func() { manager.AssertExpectations(t) })
	return manager
}
