// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	v1alpha1 "github.com/Mellanox/nic-configuration-operator/api/v1alpha1"
	types "github.com/Mellanox/nic-configuration-operator/pkg/types"

	mock "github.com/stretchr/testify/mock"
)

// ConfigurationManager is an autogenerated mock type for the ConfigurationManager type
type ConfigurationManager struct {
	mock.Mock
}

// ApplyNVConfiguration provides a mock function with given fields: ctx, device, options
func (_m *ConfigurationManager) ApplyNVConfiguration(ctx context.Context, device *v1alpha1.NicDevice, options *types.ConfigurationOptions) (*types.ConfigurationApplyResult, error) {
	ret := _m.Called(ctx, device, options)

	if len(ret) == 0 {
		panic("no return value specified for ApplyNVConfiguration")
	}

	var r0 *types.ConfigurationApplyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.NicDevice, *types.ConfigurationOptions) (*types.ConfigurationApplyResult, error)); ok {
		return rf(ctx, device, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.NicDevice, *types.ConfigurationOptions) *types.ConfigurationApplyResult); ok {
		r0 = rf(ctx, device, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ConfigurationApplyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.NicDevice, *types.ConfigurationOptions) error); ok {
		r1 = rf(ctx, device, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApplyRuntimeConfiguration provides a mock function with given fields: ctx, device
func (_m *ConfigurationManager) ApplyRuntimeConfiguration(ctx context.Context, device *v1alpha1.NicDevice) (*types.RuntimeConfigurationApplyResult, error) {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for ApplyRuntimeConfiguration")
	}

	var r0 *types.RuntimeConfigurationApplyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.NicDevice) (*types.RuntimeConfigurationApplyResult, error)); ok {
		return rf(ctx, device)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.NicDevice) *types.RuntimeConfigurationApplyResult); ok {
		r0 = rf(ctx, device)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.RuntimeConfigurationApplyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.NicDevice) error); ok {
		r1 = rf(ctx, device)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetNicFirmware provides a mock function with given fields: ctx, device
func (_m *ConfigurationManager) ResetNicFirmware(ctx context.Context, device *v1alpha1.NicDevice) error {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for ResetNicFirmware")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.NicDevice) error); ok {
		r0 = rf(ctx, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateDeviceNvSpec provides a mock function with given fields: ctx, device
func (_m *ConfigurationManager) ValidateDeviceNvSpec(ctx context.Context, device *v1alpha1.NicDevice) (bool, bool, error) {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for ValidateDeviceNvSpec")
	}

	var r0 bool
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.NicDevice) (bool, bool, error)); ok {
		return rf(ctx, device)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.NicDevice) bool); ok {
		r0 = rf(ctx, device)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.NicDevice) bool); ok {
		r1 = rf(ctx, device)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *v1alpha1.NicDevice) error); ok {
		r2 = rf(ctx, device)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewConfigurationManager creates a new instance of ConfigurationManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigurationManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigurationManager {
	mock := &ConfigurationManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
