name: "Build, Test, Lint"
on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/go-ci-reusable.yml@main
    with:
      test-command: make test
      coverage-file: cover.out
      validate-command: |
        go mod tidy
        git diff --exit-code
        make generate
        make manifests
        git diff --exit-code
