name: "Image push release"
on:
  push:
    tags:
      - v*
env:
  REGISTRY: "ghcr.io"
  OPERATOR_IMAGE_NAME: "nic-configuration-operator"
  DAEMON_IMAGE_NAME: "nic-configuration-operator-daemon"
jobs:
  image-build-push:
    name: Image build and push
    runs-on: ubuntu-latest
    steps:
      - name: Set repository owner as lower-case output variable
        id: repo_owner
        run: echo REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker operator image meta
        id: docker_meta_operator
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.OPERATOR_IMAGE_NAME }}
          tags: |
            type=ref,event=tag
          flavor: |
            latest=false
      - name: Build and push operator image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.docker_meta_operator.outputs.tags }}
          labels: ${{ steps.docker_meta_operator.outputs.labels }}
      - name: Docker daemon image meta
        id: docker_meta_daemon
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.DAEMON_IMAGE_NAME }}
          tags: |
            type=ref,event=tag
          flavor: |
            latest=false
      - name: Build and push config daemon image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.docker_meta_daemon.outputs.tags }}
          labels: ${{ steps.docker_meta_daemon.outputs.labels }}
          file: ./Dockerfile.nic-configuration-daemon
