operator:
  image:
    # -- repository to use for the operator image
    repository: ghcr.io/mellanox
    name: nic-configuration-operator
    # -- image tag to use for the operator image
    tag: latest
  # -- tolerations for the operator
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  # -- node selector for the operator
  nodeSelector: {}
  # -- node affinity for the operator
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: Exists
        - weight: 1
          preference:
            matchExpressions:
              - key: "node-role.kubernetes.io/control-plane"
                operator: Exists
  # -- specify resource requests and limits for the operator
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  # -- operator deployment number of replicas
  replicas: 1
  serviceAccount:
    # -- set annotations for the operator service account
    annotations: {}

configDaemon:
  image:
    # -- repository to use for the config daemon image
    repository: ghcr.io/mellanox
    name: nic-configuration-operator-daemon
    # -- image tag to use for the config daemon image
    tag: latest
  # -- node selector for the config daemon
  nodeSelector:
    network.nvidia.com/operator.mofed.wait: "false"
  # -- resources and limits for the config daemon
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

# -- log level configuration (debug|info)
logLevel: info
# -- image pull secrets for both the operator and the config daemon
imagePullSecrets: []

# -- settings to enable the NIC Firmware Storage
nicFirmwareStorage:
  # -- create a new pvc or use an existing one
  create: true
  # -- name of the PVC to mount as NIC Firmware storage. If set to empty string, the NIC FW upgrade feature will be disabled.
  pvcName: nic-fw-storage-pvc
  # -- storage class name to be used to store NIC FW binaries during NIC FW upgrade. If not provided, the cluster-default storage class will be used
  storageClassName: ""
  # -- storage size for the NIC Configuration Operator to request. 1Gi is the default value when not provided
  availableStorageSize: 1Gi
